In [1]:

import sys
import os
sys.path.append(os.path.abspath(".."))
import pandas as pd
from database.querys import get_movies
from database.connection import get_engine
from services.tmdb_services import get_movie_details, get_movie_credits
import json
from pprint import pprint
from database.querys import get_categories
from sqlalchemy import text

In [29]:
#Obtenemos el dataframe de la base de datos
df_movies = get_movies()
df_movies.head()

,id,title,backdrop_path,genre_ids,original_language,overview,popularity,poster_path,release_date,vote_average,vote_count
0,1318447,Apex,/9nzfyiYbmTUXWC4B2kwjl4NAlqO.jpg,"{28,53}",en,A grieving woman pushing her limits on a solo ...,420.7286,/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg,2026-04-24,6.448,660
1,1226863,The Super Mario Galaxy Movie,/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg,"{10751,35,12,14,16}",en,Having thwarted Bowser's previous plot to marr...,475.8419,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,6.700,723
2,10867,Malena,/lUbc4XVpCe1q4aqZyQqFCIubaDN.jpg,{18},it,12-year-old Renato experiences three significa...,324.4101,/3OyQTl0IGkbnjDxd3MhztfPE34g.jpg,2000-10-27,7.400,2491
3,1007757,Swapped,/wpabGmGA3IaJNGudbzGritmR8Km.jpg,"{16,10751,14}",en,A tiny woodland creature and a majestic bird s...,328.1308,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,8.136,55
4,1198994,Send Help,/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg,"{27,53,35}",en,Two colleagues become stranded on a deserted i...,273.8197,/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg,2026-01-22,7.000,1182

In [15]:
# Convertimos la columna `release_year` a datetime para mejor manipulacion
df_movies['release_date'] = pd.to_datetime(df_movies['release_date']).dt.date

In [29]:
#Ahora podemos seleccionar directamente los cambios
anios = df_movies['release_date'].apply(lambda x: x.year)
anios.min()

np.float64(1902.0)

In [14]:
categries = get_categories()
categries

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [33]:
engine = get_engine()
def get_category_name(category_id):
    query = text("""
                SELECT name
                FROM categories
                WHERE id = :category_id
                """)
    params = {"category_id":category_id}
    
    result = pd.read_sql(query, engine, params=params)
    
    if not result.empty:
        return result.iloc[0]['name']
    
    else:
        return None
    
def string_to_list(cadena):
    return [int(x) for x in cadena.strip('{}').split(',') if x]

In [26]:
get_category_name(53)

'Thriller'

In [32]:
df_apex = df_movies['genre_ids'][0]
df_apex

'{28,53}'

In [34]:
list = string_to_list(df_apex)
list

[28, 53]

In [35]:
for i in list:
    name = get_category_name(i)
    print(name)

Action
Thriller

In [ ]:

#formato para imagenes https://image.tmdb.org/t/p/w400//eJGWx219ZcEMVQJhAgMiqo8tYY.jpg

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg,"[10751, 35, 12, 14, 16]",1226863,The Super Mario Galaxy Movie,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,514.3655,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,False,False,6.744,718
1,False,/9nzfyiYbmTUXWC4B2kwjl4NAlqO.jpg,"[28, 53]",1318447,Apex,en,Apex,A grieving woman pushing her limits on a solo ...,482.8791,/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg,2026-04-24,False,False,6.400,647
2,False,/lUbc4XVpCe1q4aqZyQqFCIubaDN.jpg,[18],10867,Malena,it,Malèna,12-year-old Renato experiences three significa...,314.5536,/3OyQTl0IGkbnjDxd3MhztfPE34g.jpg,2000-10-27,False,False,7.400,2491
3,False,/wpabGmGA3IaJNGudbzGritmR8Km.jpg,"[16, 12, 35, 10751, 14]",1007757,Swapped,en,Swapped,A tiny woodland creature and a majestic bird s...,311.8469,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.200,53
4,False,/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg,"[27, 53, 35]",1198994,Send Help,en,Send Help,Two colleagues become stranded on a deserted i...,299.0156,/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg,2026-01-22,False,False,7.003,1176
5,False,/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",263.0594,/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg,2026-04-22,False,False,7.526,473
6,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,Your Heart Will Be Broken,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,257.4982,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,False,False,6.900,75
7,False,/gkh6Nt8DtY1XT4gQsyFq9XAVJlJ.jpg,"[18, 35]",350,The Devil Wears Prada,en,The Devil Wears Prada,A young woman from the Midwest gets more than ...,247.6948,/8912AsVuS7Sj915apArUFbv6F9L.jpg,2006-06-29,False,False,7.389,13146
8,False,/qnTdOizsXBzYu3uIbfhHSfE29TE.jpg,"[28, 35, 27]",1292695,They Will Kill You,en,They Will Kill You,A woman answers a help wanted ad to be a house...,245.4119,/6oI4oQKTWMVUlr8Ivqydp28Ruu6.jpg,2026-03-25,False,False,6.700,333
9,False,/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg,"[12, 16, 35, 10751, 878]",1327819,Hoppers,en,Hoppers,Scientists have discovered how to 'hop' human ...,225.6446,/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg,2026-03-04,False,False,7.700,710
10,False,/y3fQa7pytlysovXzovpXc1OQlTW.jpg,"[35, 18]",1314481,The Devil Wears Prada 2,en,The Devil Wears Prada 2,Andy Sachs returns to Runway as Miranda Priest...,215.9162,/xTI42pmsP5EDnvsNJPEDubwWBQO.jpg,2026-04-29,False,False,6.800,255
11,False,/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg,"[878, 12, 14]",83533,Avatar: Fire and Ash,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,213.5486,/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg,2025-12-17,False,False,7.367,2803
12,False,/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg,"[28, 53]",1613798,Vengeance,es,Venganza,"The brutal murder of the wife of “Toro,” a mil...",203.3633,/ygWXPL0RS91JyJPNOfK34eV3bRE.jpg,2026-02-26,False,False,7.100,125
13,False,/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",174.5823,/29Jdsak3SrwGds5k1t43kH6Khed.jpg,2026-10-09,False,False,0.000,0
14,False,/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg,"[16, 35, 10751]",1297842,GOAT,en,GOAT,A small goat with big dreams gets a once-in-a-...,155.3158,/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg,2026-02-11,False,False,7.943,484
15,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,145.0780,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.208,1911
16,False,/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg,"[28, 80, 53]",1290821,Shelter,en,Shelter,A man living in self-imposed exile on a remote...,141.5906,/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg,2026-01-28,False,False,6.812,634
17,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,139.3430,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,7.698,815
18,False,/be5T7oHxmDG4ytEimwPdmDHZD9N.jpg,[27],1352874,The Crucifix: Blood of the Exorcist,en,The Crucifix: Blood of the Exorcist,A gruesome discovery in the grounds of their n...,135.7986,/u3qOxvlykoTpurg1G8VOcawoePI.jpg,2025-01-09,False,False,5.686,35
19,False,/6D2NsU3FIQVthPgjT6RAsX58qZ6.jpg,"[28, 53, 9648, 18]",1414413,Brothers Under Fire,en,Brothers Under Fire,Captain Jordan Wright's squadron on leave for ...,132.8846,/e5EKqk9V7N3w0WvYFhl6wSVrMp0.jpg,2026-04-15,False,False,6.500,16

In [32]:
languages = df_movies['original_language'].dropna().unique()
languages

<ArrowStringArray>
['en', 'it', 'ru', 'es', 'ja', 'tl', 'zh', 'fr', 'no', 'hi', 'th', 'el', 'ro',
 'sv', 'ko', 'de', 'fi', 'pt', 'mn', 'lv', 'te', 'ml', 'da', 'cn', 'sr', 'ar',
 'ms', 'kn', 'id', 'ta', 'bn', 'af', 'mr', 'tr', 'he', 'nl', 'pl', 'pa', 'am',
 'uk', 'bg', 'ca', 'ur', 'eu', 'cs', 'xx', 'et', 'hu', 'si', 'ga', 'az', 'fa']
Length: 52, dtype: str

In [4]:
details = get_movie_details(1297842)
details

{'adult': False,
 'backdrop_path': '/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg',
 'belongs_to_collection': None,
 'budget': 90000000,
 'genres': [{'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 10751, 'name': 'Family'}],
 'homepage': 'https://goat.movie',
 'id': 1297842,
 'imdb_id': 'tt27613895',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'GOAT',
 'overview': 'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.',
 'popularity': 139.7272,
 'poster_path': '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
 'production_companies': [{'id': 2251,
   'logo_path': '/5ilV5mH3gxTEU7p5wjxptHvXkyr.png',
   'name': 'Sony Pictures Animation',
   'origin_country': 'US'},
  {'id': 120524,
   'logo_path': '/6G31NBE33avSwnSw9OGiFhCOpkS.png',
   'name': 'Unanimous Media',
   'origin_country': 'US'},
  {'id': 184287,
   'logo_path': '/yH5Zbs5SaOiXCazdQwrt00vK9Pj.png',
   'name': 'Modern Magic',
   'origin_country': 'US'},
  {'id': 5,
   'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
   'name': 'Columbia Pictures',
   'origin_country': 'US'},
  {'id': 79426,
   'logo_path': '/8aEC7xem9YwHNCDojSFEPQgoFC3.png',
   'name': 'MACRO',
   'origin_country': 'US'},
  {'id': 22213,
   'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
   'name': 'TSG Entertainment',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2026-02-11',
 'revenue': 190564590,
 'runtime': 100,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': "You're never too small to dream big.",
 'title': 'GOAT',
 'video': False,
 'vote_average': 7.939,
 'vote_count': 485}

In [11]:
pprint(details, width=800)

{'adult': False,
 'backdrop_path': '/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg',
 'belongs_to_collection': None,
 'budget': 90000000,
 'genres': [{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}],
 'homepage': 'https://goat.movie',
 'id': 1297842,
 'imdb_id': 'tt27613895',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'GOAT',
 'overview': 'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.',
 'popularity': 139.7272,
 'poster_path': '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
 'production_companies': [{'id': 2251, 'logo_path': '/5ilV5mH3gxTEU7p5wjxptHvXkyr.png', 'name': 'Sony Pictures Animation', 'origin_country': 'US'}, {'id': 120524, 'logo_path': '/6G31NBE33avSwnSw9OGiFhCOpkS.png', 'name': 'Unanimous Media', 'origin_country': 'US'}, {'id': 184287, 'logo_path': '/yH5Zbs5SaOiXCazdQwrt00vK9Pj.png', 'name': 'Modern Magic', 'origin_country': 'US'}, {'id': 5, 'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png', 'name': 'Columbia Pictures', 'origin_country': 'US'}, {'id': 79426, 'logo_path': '/8aEC7xem9YwHNCDojSFEPQgoFC3.png', 'name': 'MACRO', 'origin_country': 'US'}, {'id': 22213, 'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png', 'name': 'TSG Entertainment', 'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US', 'name': 'United States of America'}],
 'release_date': '2026-02-11',
 'revenue': 190564590,
 'runtime': 100,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}],
 'status': 'Released',
 'tagline': "You're never too small to dream big.",
 'title': 'GOAT',
 'video': False,
 'vote_average': 7.939,
 'vote_count': 485}

In [12]:
with open("movie.json", "w", encoding="utf-8") as file:
    json.dump(details, file, indent=4, ensure_ascii=False)

In [2]:
credits = get_movie_credits(1318447)
credits

{'id': 1318447,
 'cast': [{'adult': False,
   'gender': 1,
   'id': 6885,
   'known_for_department': 'Acting',
   'name': 'Charlize Theron',
   'original_name': 'Charlize Theron',
   'popularity': 17.2616,
   'profile_path': '/gd7ShD0yt4bsR2STeQ19KQ6hvXL.jpg',
   'cast_id': 1,
   'character': 'Sasha',
   'credit_id': '66994f51dd1111337fdd72c7',
   'order': 0},
  {'adult': False,
   'gender': 2,
   'id': 1303037,
   'known_for_department': 'Acting',
   'name': 'Taron Egerton',
   'original_name': 'Taron Egerton',
   'popularity': 21.7594,
   'profile_path': '/uCaPhyKAQIfEzAWWCYIrO2004CB.jpg',
   'cast_id': 13,
   'character': 'Ben',
   'credit_id': '6733cf2fa67e36bb668d74c0',
   'order': 1},
  {'adult': False,
   'gender': 2,
   'id': 8783,
   'known_for_department': 'Acting',
   'name': 'Eric Bana',
   'original_name': 'Eric Bana',
   'popularity': 5.4269,
   'profile_path': '/l9yoDgw3YFC2gMD1HTo5djGOwSY.jpg',
   'cast_id': 14,
   'character': 'Tommy',
   'credit_id': '679d10c0a9b4b128fb4d3b35',
   'order': 2},
  {'adult': False,
   'gender': 1,
   'id': 145245,
   'known_for_department': 'Acting',
   'name': 'Caitlin Stasey',
   'original_name': 'Caitlin Stasey',
   'popularity': 1.9086,
   'profile_path': '/uJW62qSjIyI0OP30s5U8KLlDw32.jpg',
   'cast_id': 30,
   'character': 'Leah',
   'credit_id': '69cbb00a9b85c1ae70ac4b5f',
   'order': 3},
  {'adult': False,
   'gender': 1,
   'id': 2933227,
   'known_for_department': 'Acting',
   'name': 'Bessie Holland',
   'original_name': 'Bessie Holland',
   'popularity': 0.695,
   'profile_path': '/pWjjlOAs61Rxy2KbAXACxL2eJ9w.jpg',
   'cast_id': 31,
   'character': 'Cashier',
   'credit_id': '69cbb0107b2f66de2dca3de7',
   'order': 4},
  {'adult': False,
   'gender': 2,
   'id': 1245420,
   'known_for_department': 'Acting',
   'name': 'Zachary Garred',
   'original_name': 'Zachary Garred',
   'popularity': 0.4234,
   'profile_path': '/zBveIZvcVCkWTcAWEV88MwpynyG.jpg',
   'cast_id': 32,
   'character': 'Sean',
   'credit_id': '69cbb018508e09665db83214',
   'order': 5},
  {'adult': False,
   'gender': 2,
   'id': 1046893,
   'known_for_department': 'Acting',
   'name': 'Matt Whelan',
   'original_name': 'Matt Whelan',
   'popularity': 0.7308,
   'profile_path': '/qTIe7SblKwxR9DF6iNuVX0pEWIZ.jpg',
   'cast_id': 38,
   'character': 'Hunter',
   'credit_id': '69ea8c54ab25fda2266b0ac7',
   'order': 6},
  {'adult': False,
   'gender': 2,
   'id': 1240306,
   'known_for_department': 'Acting',
   'name': 'Rob Carlton',
   'original_name': 'Rob Carlton',
   'popularity': 0.925,
   'profile_path': '/kv1KHqQw1ekhpFJW6vRYW3oitRQ.jpg',
   'cast_id': 40,
   'character': '2nd Hunter',
   'credit_id': '69ea8c85292b674dedb4dce8',
   'order': 7},
  {'adult': False,
   'gender': 2,
   'id': 126579,
   'known_for_department': 'Acting',
   'name': 'Aaron Pedersen',
   'original_name': 'Aaron Pedersen',
   'popularity': 1.237,
   'profile_path': '/3SoOwjIPULquiuo0yBWAwVamJFj.jpg',
   'cast_id': 39,
   'character': 'Park Ranger',
   'credit_id': '69ea8c639111265a6028c7bc',
   'order': 8},
  {'adult': False,
   'gender': 2,
   'id': 1928966,
   'known_for_department': 'Acting',
   'name': 'Duncan Fellows',
   'original_name': 'Duncan Fellows',
   'popularity': 0.2223,
   'profile_path': '/kG6EGc5dR5A0mGhTpIcxK9lkL1k.jpg',
   'cast_id': 41,
   'character': 'Dad',
   'credit_id': '69ea8c91956efb7996b4dc55',
   'order': 9},
  {'adult': False,
   'gender': 0,
   'id': 3044177,
   'known_for_department': 'Acting',
   'name': 'Julia Ohannessian',
   'original_name': 'Julia Ohannessian',
   'popularity': 0.1219,
   'profile_path': None,
   'cast_id': 42,
   'character': 'Mom',
   'credit_id': '69ea8c9a09dea8465dd47d30',
   'order': 10},
  {'adult': False,
   'gender': 0,
   'id': 6163716,
   'known_for_department': 'Acting',
   'name': 'Niam Hogan',
   'original_name': 'Niam Hogan',
   'popularity': 0.1789,
   'profile_path': None,
   'cast_id': 43,
   'character': 'Boy',
   'credit_id': '69ea8ce6efc287ff9c935196',
   'order': 11},
  {'adult': False,
   'gender': 0,
   'id': 6163717,
   'known_for_department': 'Acting',
   'name': 'Willow Seager',
   'original_name': 'Willow Seager',
   'popularity': 0.1429,
   'profile_path': None,
   'cast_id': 44,
   'character': 'Teenage Daughter',
   'credit_id': '69ea8cf9b724addfa717c3ed',
   'order': 12}],
 'crew': [{'adult': False,
   'gender': 2,
   'id': 67813,
   'known_for_department': 'Directing',
   'name': 'Baltasar Kormákur',
   'original_name': 'Baltasar Kormákur',
   'popularity': 1.9087,
   'profile_path': '/bpWHj7MUtv0bNRuCET69UWQRa0o.jpg',
   'credit_id': '6699501d36ea3db3e93a786c',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 2,
   'id': 67813,
   'known_for_department': 'Directing',
   'name': 'Baltasar Kormákur',
   'original_name': 'Baltasar Kormákur',
   'popularity': 1.9087,
   'profile_path': '/bpWHj7MUtv0bNRuCET69UWQRa0o.jpg',
   'credit_id': '66994f65ec421a95b378d2dd',
   'department': 'Directing',
   'job': 'Director'},
  {'adult': False,
   'gender': 1,
   'id': 6885,
   'known_for_department': 'Acting',
   'name': 'Charlize Theron',
   'original_name': 'Charlize Theron',
   'popularity': 17.2616,
   'profile_path': '/gd7ShD0yt4bsR2STeQ19KQ6hvXL.jpg',
   'credit_id': '66994fb883d72d0f384cd6f0',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 1,
   'id': 1117873,
   'known_for_department': 'Production',
   'name': 'Beth Kono',
   'original_name': 'Beth Kono',
   'popularity': 0.5645,
   'profile_path': None,
   'credit_id': '66994fcca2c18818363a786c',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 2,
   'id': 266920,
   'known_for_department': 'Production',
   'name': 'Peter Chernin',
   'original_name': 'Peter Chernin',
   'popularity': 0.7975,
   'profile_path': '/6c7tilaP8n2bYJB0H6BZyEkd64k.jpg',
   'credit_id': '66995047ece1ee1639c50f29',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 1,
   'id': 36427,
   'known_for_department': 'Production',
   'name': 'Jenno Topping',
   'original_name': 'Jenno Topping',
   'popularity': 0.8514,
   'profile_path': '/tOti87QZZwyBp1iujzPTib9AwuU.jpg',
   'credit_id': '66995054ed155a645289df02',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 2,
   'id': 1106752,
   'known_for_department': 'Production',
   'name': 'David Ready',
   'original_name': 'David Ready',
   'popularity': 0.3213,
   'profile_path': '/9AEaXCiXkUHHjup3staUsVLxtl7.jpg',
   'credit_id': '669950605b41020596fd70eb',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 2,
   'id': 9987,
   'known_for_department': 'Production',
   'name': 'Ian Bryce',
   'original_name': 'Ian Bryce',
   'popularity': 0.8655,
   'profile_path': '/y45uZM4RTXmC02XwsMseFMObUAF.jpg',
   'credit_id': '6699503a173d6648bec50f2a',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 0,
   'id': 20222,
   'known_for_department': 'Production',
   'name': 'A.J. Dix',
   'original_name': 'A.J. Dix',
   'popularity': 0.3035,
   'profile_path': None,
   'credit_id': '66994fd83e9900c9c14d0dcf',
   'department': 'Production',
   'job': 'Producer'},
  {'adult': False,
   'gender': 0,
   'id': 1578013,
   'known_for_department': 'Production',
   'name': 'Amanda Mitchell',
   'original_name': 'Amanda Mitchell',
   'popularity': 0.1994,
   'profile_path': None,
   'credit_id': '68716003511d589e4e704af0',
   'department': 'Production',
   'job': 'Casting'},
  {'adult': False,
   'gender': 2,
   'id': 37768,
   'known_for_department': 'Art',
   'name': 'Jean-Vincent Puzos',
   'original_name': 'Jean-Vincent Puzos',
   'popularity': 0.3318,
   'profile_path': '/2jyrIxAHVVJZmWNHVDJNPqwCbc7.jpg',
   'credit_id': '687160108a675c21b2704890',
   'department': 'Art',
   'job': 'Production Design'},
  {'adult': False,
   'gender': 1,
   'id': 1034192,
   'known_for_department': 'Art',
   'name': 'Sophie Nash',
   'original_name': 'Sophie Nash',
   'popularity': 0.1301,
   'profile_path': None,
   'credit_id': '6871601daf6b528508ed77ef',
   'department': 'Art',
   'job': 'Supervising Art Director'},
  {'adult': False,
   'gender': 1,
   'id': 928371,
   'known_for_department': 'Costume & Make-Up',
   'name': 'Margot Wilson',
   'original_name': 'Margot Wilson',
   'popularity': 0.3217,
   'profile_path': None,
   'credit_id': '6871602c62e78c9e6c9a5e39',
   'department': 'Costume & Make-Up',
   'job': 'Costume Design'},
  {'adult': False,
   'gender': 0,
   'id': 3073122,
   'known_for_department': 'Directing',
   'name': 'Harpa Elísa Þórsdóttir',
   'original_name': 'Harpa Elísa Þórsdóttir',
   'popularity': 0.1906,
   'profile_path': None,
   'credit_id': '687160645504f6cd90ed7731',
   'department': 'Directing',
   'job': 'First Assistant Director'},
  {'adult': False,
   'gender': 2,
   'id': 1463682,
   'known_for_department': 'Crew',
   'name': 'Greg Rementer',
   'original_name': 'Greg Rementer',
   'popularity': 0.4884,
   'profile_path': '/vLuhZfvf6EgZ0imQSDi6tmmdQNn.jpg',
   'credit_id': '68716081a38e6c90e9ed77b4',
   'department': 'Directing',
   'job': 'Second Unit Director'},
  {'adult': False,
   'gender': 2,
   'id': 1463682,
   'known_for_department': 'Crew',
   'name': 'Greg Rementer',
   'original_name': 'Greg Rementer',
   'popularity': 0.4884,
   'profile_path': '/vLuhZfvf6EgZ0imQSDi6tmmdQNn.jpg',
   'credit_id': '6871608588dc95a8ddba2f3b',
   'department': 'Crew',
   'job': 'Stunt Coordinator'},
  {'adult': False,
   'gender': 0,
   'id': 2476623,
   'known_for_department': 'Camera',
   'name': 'Phil Arntz',
   'original_name': 'Phil Arntz',
   'popularity': 0.3146,
   'profile_path': None,
   'credit_id': '687160b6f3fe3cf5cb6e9c73',
   'department': 'Camera',
   'job': 'Aerial Director of Photography'},
  {'adult': False,
   'gender': 2,
   'id': 5387,
   'known_for_department': 'Camera',
   'name': 'Lawrence Sher',
   'original_name': 'Lawrence Sher',
   'popularity': 0.4514,
   'profile_path': '/rcbHwQpmvw848ZvHaithgh7oNuF.jpg',
   'credit_id': '687160e50849184ac2ba2e74',
   'department': 'Camera',
   'job': 'Director of Photography'},
  {'adult': False,
   'gender': 1,
   'id': 1215768,
   'known_for_department': 'Production',
   'name': 'Dawn Olmstead',
   'original_name': 'Dawn Olmstead',
   'popularity': 0.2111,
   'profile_path': '/yacKhcwoQ8GyBRdD87nbqXu0qEC.jpg',
   'credit_id': '694da2b3763d7ced0b2fb66b',
   'department': 'Production',
   'job': 'Executive Producer'},
  {'adult': False,
   'gender': 2,
   'id': 71556,
   'known_for_department': 'Production',
   'name': 'Ray Angelic',
   'original_name': 'Ray Angelic',
   'popularity': 0.4267,
   'profile_path': None,
   'credit_id': '694da2d20764ddda658eaefe',
   'department': 'Production',
   'job': 'Executive Producer'},
  {'adult': False,
   'gender': 2,
   'id': 2369718,
   'known_for_department': 'Production',
   'name': 'Will McCance',
   'original_name': 'Will McCance',
   'popularity': 0.1083,
   'profile_path': None,
   'credit_id': '694da2d75bf3702a7b8eae99',
   'department': 'Production',
   'job': 'Executive Producer'},
  {'adult': False,
   'gender': 0,
   'id': 2157972,
   'known_for_department': 'Visual Effects',
   'name': 'Enrik Pavdeja',
   'original_name': 'Enrik Pavdeja',
   'popularity': 0.5375,
   'profile_path': None,
   'credit_id': '69c58640375ae2c2c1833f54',
   'department': 'Visual Effects',
   'job': 'Visual Effects Supervisor'},
  {'adult': False,
   'gender': 0,
   'id': 1558432,
   'known_for_department': 'Visual Effects',
   'name': 'Gavin Round',
   'original_name': 'Gavin Round',
   'popularity': 0.1572,
   'profile_path': None,
   'credit_id': '69c5864f67a5a6da1062cee7',
   'department': 'Visual Effects',
   'job': 'Visual Effects Producer'},
  {'adult': False,
   'gender': 2,
   'id': 131413,
   'known_for_department': 'Crew',
   'name': 'Mike Gunther',
   'original_name': 'Mike Gunther',
   'popularity': 0.7998,
   'profile_path': '/5ZbAmoeQxUOqzk1YWN5uaKJ7N2q.jpg',
   'credit_id': '69e976b5f1a3b185f76b20bc',
   'department': 'Crew',
   'job': 'Stunt Coordinator'},
  {'adult': False,
   'gender': 1,
   'id': 1848082,
   'known_for_department': 'Acting',
   'name': 'Jacqueline Lee Geurts',
   'original_name': 'Jacqueline Lee Geurts',
   'popularity': 0.3875,
   'profile_path': '/9YcJF1avZliG3Mu01mUQxuiUuu4.jpg',
   'credit_id': '69e976baba61042fd30f4c84',
   'department': 'Crew',
   'job': 'Stunt Double'},
  {'adult': False,
   'gender': 0,
   'id': 3049132,
   'known_for_department': 'Acting',
   'name': 'Brianna Pannekoek',
   'original_name': 'Brianna Pannekoek',
   'popularity': 0.0621,
   'profile_path': None,
   'credit_id': '69e976c3f1a3b185f76b20bf',
   'department': 'Crew',
   'job': 'Stunt Double'},
  {'adult': False,
   'gender': 0,
   'id': 3644695,
   'known_for_department': 'Crew',
   'name': 'Tarah Smyth',
   'original_name': 'Tarah Smyth',
   'popularity': 0.0615,
   'profile_path': None,
   'credit_id': '69e976ddb5890717e0bcb276',
   'department': 'Crew',
   'job': 'Stunt Double'},
  {'adult': False,
   'gender': 0,
   'id': 2144860,
   'known_for_department': 'Production',
   'name': 'Andrew Emilio DeCesare',
   'original_name': 'Andrew Emilio DeCesare',
   'popularity': 0.1631,
   'profile_path': None,
   'credit_id': '69e976fa3c203d0f0ccd2f6d',
   'department': 'Crew',
   'job': 'Stunts'},
  {'adult': False,
   'gender': 2,
   'id': 1709589,
   'known_for_department': 'Directing',
   'name': 'Jeremy Robbins',
   'original_name': 'Jeremy Robbins',
   'popularity': 0.4194,
   'profile_path': None,
   'credit_id': '69eb5c2c1e296fcc89935590',
   'department': 'Writing',
   'job': 'Writer'},
  {'adult': False,
   'gender': 0,
   'id': 5729891,
   'known_for_department': 'Crew',
   'name': 'Tobias Keip',
   'original_name': 'Tobias Keip',
   'popularity': 0.0327,
   'profile_path': None,
   'credit_id': '69ee12c5325625ab15dc8539',
   'department': 'Crew',
   'job': 'CG Supervisor'},
  {'adult': False,
   'gender': 0,
   'id': 1183126,
   'known_for_department': 'Editing',
   'name': 'Sigurður Eyþórsson',
   'original_name': 'Sigurður Eyþórsson',
   'popularity': 0.275,
   'profile_path': None,
   'credit_id': '69ee13503a62d9fae2150f81',
   'department': 'Editing',
   'job': 'Editor'},
  {'adult': False,
   'gender': 0,
   'id': 2647144,
   'known_for_department': 'Directing',
   'name': 'Jay Corry',
   'original_name': 'Jay Corry',
   'popularity': 0.2708,
   'profile_path': None,
   'credit_id': '69ee139948976ea43e6b1f80',
   'department': 'Directing',
   'job': 'Second Assistant Director'},
  {'adult': False,
   'gender': 2,
   'id': 1081090,
   'known_for_department': 'Acting',
   'name': 'Baltasar Breki Samper',
   'original_name': 'Baltasar Breki Samper',
   'popularity': 0.2123,
   'profile_path': '/cU1kHRsVfsHb6vhf59gEmj3FSXZ.jpg',
   'credit_id': '69ee13c7e21477a6fa9368b4',
   'department': 'Directing',
   'job': 'Second Unit Director'},
  {'adult': False,
   'gender': 1,
   'id': 2248475,
   'known_for_department': 'Sound',
   'name': 'Kirsten Lane',
   'original_name': 'Kirsten Lane',
   'popularity': 0.7616,
   'profile_path': None,
   'credit_id': '69ee13ee1189724a7a02939d',
   'department': 'Sound',
   'job': 'Music Supervisor'},
  {'adult': False,
   'gender': 0,
   'id': 2711815,
   'known_for_department': 'Visual Effects',
   'name': 'Fiona Crawford',
   'original_name': 'Fiona Crawford',
   'popularity': 0.1909,
   'profile_path': None,
   'credit_id': '69ee13f88179458295dc85f5',
   'department': 'Visual Effects',
   'job': 'Visual Effects Producer'},
  {'adult': False,
   'gender': 2,
   'id': 40810,
   'known_for_department': 'Sound',
   'name': 'Glenn Freemantle',
   'original_name': 'Glenn Freemantle',
   'popularity': 0.9193,
   'profile_path': '/qbPg2w1AoSVrbHJbQUbs9P5jD8y.jpg',
   'credit_id': '69ee14182eff35f2c56b1da9',
   'department': 'Sound',
   'job': 'Supervising Sound Editor'},
  {'adult': False,
   'gender': 2,
   'id': 40810,
   'known_for_department': 'Sound',
   'name': 'Glenn Freemantle',
   'original_name': 'Glenn Freemantle',
   'popularity': 0.9193,
   'profile_path': '/qbPg2w1AoSVrbHJbQUbs9P5jD8y.jpg',
   'credit_id': '69ee141ef8f45fa6f8150e58',
   'department': 'Sound',
   'job': 'Sound Designer'},
  {'adult': False,
   'gender': 2,
   'id': 3052670,
   'known_for_department': 'Editing',
   'name': 'Guðlaugur Andri Eythórsson',
   'original_name': 'Guðlaugur Andri Eythórsson',
   'popularity': 0.0453,
   'profile_path': None,
   'credit_id': '69ee142abdcf0e39de150dbf',
   'department': 'Editing',
   'job': 'Associate Editor'},
  {'adult': False,
   'gender': 2,
   'id': 1970824,
   'known_for_department': 'Acting',
   'name': 'Philip Partridge',
   'original_name': 'Philip Partridge',
   'popularity': 0.1666,
   'profile_path': '/xig8Q6iCMQ0laNGdDSeTTACllMA.jpg',
   'credit_id': '69ee145049d38c9361d49015',
   'department': 'Crew',
   'job': 'Stunt Coordinator'},
  {'adult': False,
   'gender': 2,
   'id': 1816359,
   'known_for_department': 'Art',
   'name': 'Tony Drew',
   'original_name': 'Tony Drew',
   'popularity': 0.2699,
   'profile_path': None,
   'credit_id': '69ee147ae807216955d491f2',
   'department': 'Art',
   'job': 'Art Direction'},
  {'adult': False,
   'gender': 0,
   'id': 2144743,
   'known_for_department': 'Art',
   'name': 'Dale Mackie',
   'original_name': 'Dale Mackie',
   'popularity': 0.0869,
   'profile_path': None,
   'credit_id': '69ee14839534e3dc84d4902c',
   'department': 'Art',
   'job': 'Art Direction'},
  {'adult': False,
   'gender': 0,
   'id': 2580334,
   'known_for_department': 'Art',
   'name': 'Paul Sarpi',
   'original_name': 'Paul Sarpi',
   'popularity': 0.1213,
   'profile_path': None,
   'credit_id': '69ee149bbf2b03e7adb4efe0',
   'department': 'Art',
   'job': 'Set Decoration'},
  {'adult': False,
   'gender': 2,
   'id': 1457359,
   'known_for_department': 'Camera',
   'name': 'Simon Harding',
   'original_name': 'Simon Harding',
   'popularity': 0.314,
   'profile_path': None,
   'credit_id': '69ee14af49195dfd37dc86e9',
   'department': 'Camera',
   'job': '"A" Camera Operator'},
  {'adult': False,
   'gender': 2,
   'id': 1457359,
   'known_for_department': 'Camera',
   'name': 'Simon Harding',
   'original_name': 'Simon Harding',
   'popularity': 0.314,
   'profile_path': None,
   'credit_id': '69ee14b4bd990e84d6b4f285',
   'department': 'Camera',
   'job': 'Steadicam Operator'},
  {'adult': False,
   'gender': 2,
   'id': 1081090,
   'known_for_department': 'Acting',
   'name': 'Baltasar Breki Samper',
   'original_name': 'Baltasar Breki Samper',
   'popularity': 0.2123,
   'profile_path': '/cU1kHRsVfsHb6vhf59gEmj3FSXZ.jpg',
   'credit_id': '69ee14cafe46622965dc872b',
   'department': 'Camera',
   'job': '"C" Camera Operator'},
  {'adult': False,
   'gender': 0,
   'id': 1906354,
   'known_for_department': 'Lighting',
   'name': 'Steve Daley',
   'original_name': 'Steve Daley',
   'popularity': 0.2603,
   'profile_path': None,
   'credit_id': '69ee14f8325625ab15dc8543',
   'department': 'Lighting',
   'job': 'Gaffer'},
  {'adult': False,
   'gender': 0,
   'id': 2144227,
   'known_for_department': 'Visual Effects',
   'name': 'Gavin McKenzie',
   'original_name': 'Gavin McKenzie',
   'popularity': 0.2302,
   'profile_path': None,
   'credit_id': '69ee1537ff48c8f5ea6b1eba',
   'department': 'Visual Effects',
   'job': 'Visual Effects Supervisor'},
  {'adult': False,
   'gender': 0,
   'id': 6169232,
   'known_for_department': 'Visual Effects',
   'name': 'Mark Gostlow',
   'original_name': 'Mark Gostlow',
   'popularity': 0.0825,
   'profile_path': None,
   'credit_id': '69ee1559389879991a02963d',
   'department': 'Visual Effects',
   'job': 'Compositing Supervisor'},
  {'adult': False,
   'gender': 0,
   'id': 6169233,
   'known_for_department': 'Crew',
   'name': 'Martina Chakarova',

In [4]:
crew = credits['crew']
director = next(
    (person["name"] for person in crew if person["job"] == "Director"),
    None
)
director

'Baltasar Kormákur'

In [5]:
cast = credits['cast']
top_cast = [actor['name'] for actor in cast[:5]]
top_cast

['Charlize Theron',
 'Taron Egerton',
 'Eric Bana',
 'Caitlin Stasey',
 'Bessie Holland']

In [7]:
engine = get_engine()
query = text("""
             SELECT DISTINCT(original_language)
             FROM movies
             """)

df_languages = pd.read_sql(query, engine )
df_languages

   original_language
0                 sr
1                 fr
2                 pa
3                 tr
4                 si
5                 en
6                 hi
7                 bg
8                 uk
9                 fi
10                ru
11                he
12                mr
13                fa
14                xx
15                cs
16                ja
17                cn
18                sv
19                am
20                kn
21                az
22                bn
23                de
24                te
25                ro
26                nl
27                ta
28                mn
29                id
30                tl
31                ms
32                et
33                ar
34                th
35                no
36                pt
37                pl
38                ko
39                el
40                zh
41                ml
42                it
43                lv
44                es
45                da
46                ga

In [8]:
df_languages['original_language'].tolist()

['sr',
 'fr',
 'pa',
 'tr',
 'si',
 'en',
 'hi',
 'bg',
 'uk',
 'fi',
 'ru',
 'he',
 'mr',
 'fa',
 'xx',
 'cs',
 'ja',
 'cn',
 'sv',
 'am',
 'kn',
 'az',
 'bn',
 'de',
 'te',
 'ro',
 'nl',
 'ta',
 'mn',
 'id',
 'tl',
 'ms',
 'et',
 'ar',
 'th',
 'no',
 'pt',
 'pl',
 'ko',
 'el',
 'zh',
 'ml',
 'it',
 'lv',
 'es',
 'da',
 'ga']